spring.application.name=Sakany

spring.datasource.url=jdbc:postgresql://localhost:5432/sakany
spring.datasource.username=sakany
spring.datasource.password=sakany_local_dev_2024

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration